---
version: "1.0"

volumes:
  data:

services:
  weewx:
    build:
      args:
        - VERSION=4.2.0
      context: .
      dockerfile: Dockerfile
    image: ksperow/weewx:4.2.0
    init: true
    restart: "no"
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - TIMEZONE=US/Eastern
      - WEEWX_UID=weewx
      - WEEWX_GID=dialout
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
